CATALOGUE_HOST: catalogue.backend-{{ env }}.kalyanu.xyz
USER_HOST: user.backend-{{ env }}.kalyanu.xyz
CART_HOST: cart.backend-{{ env }}.kalyanu.xyz
SHIPPING_HOST: shipping.backend-{{ env }}.kalyanu.xyz
PAYMENT_HOST: payment.backend-{{ env }}.kalyanu.xyz